package Commons.SharedEnums;

 
public enum ArtType {
    PAINTING,
    SCULPTURE,
    PHOTOGRAPHY,
    DRAWING,
    MIXED_MEDIA,
    PRINTMAKING,
    INSTALLATION,
    PERFORMANCE_ART,
    TEXTILE_ART,
    CERAMICS,
    DIGITAL_ART,
    VIDEO_ART,
    COLLAGE,
    ASSEMBLAGE,
    LAND_ART,
    CONCEPTUAL_ART,
    ENVIRONMENTAL_ART,
    STREET_ART,
    ABSTRACT_ART,
    REALISM,
    IMPRESSIONISM,
    EXPRESSIONISM,
    SURREALISM,
    POP_ART,
    MINIMALISM,
    CONTEMPORARY_ART
    
}
